//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由WEF.ModelGenerator, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null生成;时间 2018-11-12 14:37:16.029
//     运行时版本:4.0.30319.42000
//     不建议手动更改此代码，如有需要请自行扩展partial类
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Runtime.Serialization;
using WEF;
using WEF.Common;
using WEF.Section;
using System.Collections.Generic;

namespace WebBaseFrame.Models
{

	/// <summary>
	/// 实体类Article
	/// </summary>
	[Serializable, DataContract]
	public partial class Article : Entity 
	{
		private static string m_tableName;
		public Article():base("Article") {m_tableName="Article";}
		public Article(string tableName):base(tableName) { m_tableName=tableName;}

		#region Model
		private int _ID;
		private int? _SortID;
		private int _KID;
		private string _Title;
		private string _Summary;
		private string _KeyWords;
		private string _Content;
		private string _Quote;
		private string _Thumbs;
		private string _Files;
		private DateTime? _CreateDate;
		private int? _CreateUserID;
		private DateTime? _LastUpdateDate;
		private int? _LastUpdateUserID;
		private bool? _IsDeleted;
		/// <summary>
		/// ID 
		/// </summary>
		[DataMember]
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange(_.ID,_ID,value);
				this._ID=value;
			}
		}
		/// <summary>
		/// SortID 
		/// </summary>
		[DataMember]
		public int? SortID
		{
			get{ return _SortID; }
			set
			{
				this.OnPropertyValueChange(_.SortID,_SortID,value);
				this._SortID=value;
			}
		}
		/// <summary>
		/// KID 
		/// </summary>
		[DataMember]
		public int KID
		{
			get{ return _KID; }
			set
			{
				this.OnPropertyValueChange(_.KID,_KID,value);
				this._KID=value;
			}
		}
		/// <summary>
		/// Title 
		/// </summary>
		[DataMember]
		public string Title
		{
			get{ return _Title; }
			set
			{
				this.OnPropertyValueChange(_.Title,_Title,value);
				this._Title=value;
			}
		}
		/// <summary>
		/// Summary 
		/// </summary>
		[DataMember]
		public string Summary
		{
			get{ return _Summary; }
			set
			{
				this.OnPropertyValueChange(_.Summary,_Summary,value);
				this._Summary=value;
			}
		}
		/// <summary>
		/// KeyWords 
		/// </summary>
		[DataMember]
		public string KeyWords
		{
			get{ return _KeyWords; }
			set
			{
				this.OnPropertyValueChange(_.KeyWords,_KeyWords,value);
				this._KeyWords=value;
			}
		}
		/// <summary>
		/// Content 
		/// </summary>
		[DataMember]
		public string Content
		{
			get{ return _Content; }
			set
			{
				this.OnPropertyValueChange(_.Content,_Content,value);
				this._Content=value;
			}
		}
		/// <summary>
		/// Quote 
		/// </summary>
		[DataMember]
		public string Quote
		{
			get{ return _Quote; }
			set
			{
				this.OnPropertyValueChange(_.Quote,_Quote,value);
				this._Quote=value;
			}
		}
		/// <summary>
		/// Thumbs 
		/// </summary>
		[DataMember]
		public string Thumbs
		{
			get{ return _Thumbs; }
			set
			{
				this.OnPropertyValueChange(_.Thumbs,_Thumbs,value);
				this._Thumbs=value;
			}
		}
		/// <summary>
		/// Files 
		/// </summary>
		[DataMember]
		public string Files
		{
			get{ return _Files; }
			set
			{
				this.OnPropertyValueChange(_.Files,_Files,value);
				this._Files=value;
			}
		}
		/// <summary>
		/// CreateDate 
		/// </summary>
		[DataMember]
		public DateTime? CreateDate
		{
			get{ return _CreateDate; }
			set
			{
				this.OnPropertyValueChange(_.CreateDate,_CreateDate,value);
				this._CreateDate=value;
			}
		}
		/// <summary>
		/// CreateUserID 
		/// </summary>
		[DataMember]
		public int? CreateUserID
		{
			get{ return _CreateUserID; }
			set
			{
				this.OnPropertyValueChange(_.CreateUserID,_CreateUserID,value);
				this._CreateUserID=value;
			}
		}
		/// <summary>
		/// LastUpdateDate 
		/// </summary>
		[DataMember]
		public DateTime? LastUpdateDate
		{
			get{ return _LastUpdateDate; }
			set
			{
				this.OnPropertyValueChange(_.LastUpdateDate,_LastUpdateDate,value);
				this._LastUpdateDate=value;
			}
		}
		/// <summary>
		/// LastUpdateUserID 
		/// </summary>
		[DataMember]
		public int? LastUpdateUserID
		{
			get{ return _LastUpdateUserID; }
			set
			{
				this.OnPropertyValueChange(_.LastUpdateUserID,_LastUpdateUserID,value);
				this._LastUpdateUserID=value;
			}
		}
		/// <summary>
		/// IsDeleted 
		/// </summary>
		[DataMember]
		public bool? IsDeleted
		{
			get{ return _IsDeleted; }
			set
			{
				this.OnPropertyValueChange(_.IsDeleted,_IsDeleted,value);
				this._IsDeleted=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.ID;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ID,
				_.SortID,
				_.KID,
				_.Title,
				_.Summary,
				_.KeyWords,
				_.Content,
				_.Quote,
				_.Thumbs,
				_.Files,
				_.CreateDate,
				_.CreateUserID,
				_.LastUpdateDate,
				_.LastUpdateUserID,
				_.IsDeleted};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ID,
				this._SortID,
				this._KID,
				this._Title,
				this._Summary,
				this._KeyWords,
				this._Content,
				this._Quote,
				this._Thumbs,
				this._Files,
				this._CreateDate,
				this._CreateUserID,
				this._LastUpdateDate,
				this._LastUpdateUserID,
				this._IsDeleted};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// Article 
			/// </summary>
			public readonly static Field All = new Field("*",m_tableName);
			/// <summary>
			/// ID 
			/// </summary>
			public readonly static Field ID = new Field("ID",m_tableName,"ID");
			/// <summary>
			/// SortID 
			/// </summary>
			public readonly static Field SortID = new Field("SortID",m_tableName,"SortID");
			/// <summary>
			/// KID 
			/// </summary>
			public readonly static Field KID = new Field("KID",m_tableName,"KID");
			/// <summary>
			/// Title 
			/// </summary>
			public readonly static Field Title = new Field("Title",m_tableName,"Title");
			/// <summary>
			/// Summary 
			/// </summary>
			public readonly static Field Summary = new Field("Summary",m_tableName,"Summary");
			/// <summary>
			/// KeyWords 
			/// </summary>
			public readonly static Field KeyWords = new Field("KeyWords",m_tableName,"KeyWords");
			/// <summary>
			/// Content 
			/// </summary>
			public readonly static Field Content = new Field("Content",m_tableName,"Content");
			/// <summary>
			/// Quote 
			/// </summary>
			public readonly static Field Quote = new Field("Quote",m_tableName,"Quote");
			/// <summary>
			/// Thumbs 
			/// </summary>
			public readonly static Field Thumbs = new Field("Thumbs",m_tableName,"Thumbs");
			/// <summary>
			/// Files 
			/// </summary>
			public readonly static Field Files = new Field("Files",m_tableName,"Files");
			/// <summary>
			/// CreateDate 
			/// </summary>
			public readonly static Field CreateDate = new Field("CreateDate",m_tableName,"CreateDate");
			/// <summary>
			/// CreateUserID 
			/// </summary>
			public readonly static Field CreateUserID = new Field("CreateUserID",m_tableName,"CreateUserID");
			/// <summary>
			/// LastUpdateDate 
			/// </summary>
			public readonly static Field LastUpdateDate = new Field("LastUpdateDate",m_tableName,"LastUpdateDate");
			/// <summary>
			/// LastUpdateUserID 
			/// </summary>
			public readonly static Field LastUpdateUserID = new Field("LastUpdateUserID",m_tableName,"LastUpdateUserID");
			/// <summary>
			/// IsDeleted 
			/// </summary>
			public readonly static Field IsDeleted = new Field("IsDeleted",m_tableName,"IsDeleted");
		}
		#endregion


	}
	/// <summary>
	/// 实体类Article操作类
	/// </summary>
	public partial class ArticleRepository
	{
		DBContext db;
		/// <summary>
		/// 当前实体查询上下文
		/// </summary>
		public ISearch<Article> Search(string tableName="")
		{
			if (string.IsNullOrEmpty(tableName))
			{
				tableName="Article";
			}
				return db.Search<Article>(tableName);
		}
		/// <summary>
		/// 当前实体查询上下文
		/// </summary>
		public ISearch<Article> Search(Article entity)
		{
				return db.Search<Article>(entity);
		}
		/// <summary>
		/// 构造方法
		/// </summary>
		public ArticleRepository()
		{
			db = new DBContext();
		}
		/// <summary>
		/// 构造方法
		/// <param name="connStrName">连接字符串中的名称</param>
		/// </summary>
		public ArticleRepository(string connStrName)
		{
			db = new DBContext(connStrName);
		}
		/// <summary>
		/// 当前db操作上下文
		/// </summary>
		public DBContext DBContext
		{
			get
			{
				return db;
			}
		}
		/// <summary>
		/// 获取实体
		/// <param name="pageIndex">分页第几页</param>
		/// <param name="pageSize">分页一页取值</param>
		/// </summary>
		public Article GetArticle(int id)
		{
			return Search().Where(b => b.ID == id).First();
		}
		/// <summary>
		/// 获取列表
		/// <param name="pageIndex">分页第几页</param>
		/// <param name="pageSize">分页一页取值</param>
		/// </summary>
		public List<Article> GetList(int pageIndex, int pageSize)
		{
			return this.Search().Page(pageIndex, pageSize).ToList();
		}
		/// <summary>
		/// 获取列表
		/// <param name="tableName">表名</param>
		/// <param name="pageIndex">分页第几页</param>
		/// <param name="pageSize">分页一页取值</param>
		/// </summary>
		public List<Article> GetList(string tableName, int pageIndex=1, int pageSize=12)
		{
			return this.Search(tableName).Page(pageIndex, pageSize).ToList();
		}
		/// <summary>
		/// 添加实体
		/// <param name="obj">传进的实体</param>
		/// </summary>
		public int Insert(Article obj)
		{
			return db.Insert(obj);
		}
		/// <summary>
		/// 更新实体
		/// <param name="obj">传进的实体</param>
		/// </summary>
		public int Update(Article obj)
		{
			return db.Update(obj);
		}
		/// <summary>
		/// 删除实体
		/// <param name="obj">传进的实体</param>
		/// </summary>
		public int Delete(Article obj)
		{
			return db.Delete(obj);
		}
		/// <summary>
		/// 删除实体
		/// <param name="id">id</param>
		/// </summary>
		public int Delete(int id)
		{
			var obj = Search().Where(b => b.ID == id).First();
			return db.Delete(obj);
		}
		/// <summary>
		/// 批量删除实体
		/// <param name="obj">传进的实体列表</param>
		/// </summary>
		public int Deletes(List<Article> objs)
		{
			return db.Delete<Article>(objs);
		}
		/// <summary>
		/// 执行sql语句
		/// <param name="sql"></param>
		/// </summary>
		public SqlSection ExecuteSQL(string sql)
		{
			return db.FromSql(sql);
		}
		/// <summary>
		/// 执行存储过程
		/// <param name="sql"></param>
		/// </summary>
		public ProcSection ExcuteProc(string procName)
		{
			return db.FromProc(procName);
		}
	}

}

