DECLARE @ID INT
DECLARE myCur CURSOR
FOR
    SELECT  ID
    FROM    [Area] AS a
OPEN myCur
FETCH NEXT FROM myCur INTO @ID
WHILE @@FETCH_STATUS = 0
    BEGIN


        FETCH NEXT FROM myCur INTO @ID
    END
CLOSE myCur
DEALLOCATE myCur